version: '3.3'
volumes:
  pg_data_local:
  static:

services:
  db_network:
    image: postgres:15.3
    env_file: .env
    volumes:
      - pg_data_local:/var/lib/postgresql/data
  backend:
    build:
      context: ../pay
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - static:/static_backend
    depends_on:
      - db_network
  nginx:
    image: nginx:1.19.3
    ports:
      - "8000:80"
    volumes:
      - ../infra/nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/staticfiles